name: Bank Login CI/CD

on:
  push:
    branches:
      - main

env:
  FRONTEND_IMAGE: mad0008271/bank-login-frontend
  BACKEND_IMAGE: mad0008271/bank-login-backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend
        run: |
          docker build -t $FRONTEND_IMAGE:latest .

      - name: Build Backend
        run: |
          docker build -t $BACKEND_IMAGE:latest ./backend

      - name: Push Frontend
        run: |
          docker push $FRONTEND_IMAGE:latest

      - name: Push Backend
        run: |
          docker push $BACKEND_IMAGE:latest